services:
  - type: web
    name: webshell
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SHELL_PASSWORD
        sync: false
      - key: MODE
        value: local
      - key: HOST
        value: 0.0.0.0
      - key: ENABLE_DESKTOP
        value: "true"
      - key: DISPLAY
        value: ":99"
